version: '2'
services:
  db:
    image: mysql
    env_file:
      - environnements/database.env
    networks:
        - app_net
    restart: always
  web:
    build: .
    #image: tanguybron/securkey:web
    env_file:
      - environnements/django.env
      - environnements/database.env
    command:
      - /bin/bash
      - -c
      - |
        sleep 15
        python3 manage.py makemigrations
        python3 manage.py migrate
        gunicorn --bind 0.0.0.0:8000 mdpManagerTest.wsgi
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - app_net
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    #image: tanguybron/securkey:nginx
    volumes:
      - .:/code
    ports:
      - "443:443"
    depends_on:
      - web
    networks:
      - app_net
    restart: always

networks :
  app_net:
