version: '2'
services:
  db:
    build: bdd/.
    environment:
        MYSQL_DATABASE: MdPManager
        MYSQL_USER: user
        MYSQL_PASSWORD: azerty
        MYSQL_ROOT_PASSWORD: azerty
    volumes:
        - ./bdd:/docker-entrypoint-initdb.d
    networks:
        - app_net
  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        python3 manage.py migrate
        gunicorn --bind 0.0.0.0:8000 mdpManagerTest.wsgi
        # python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - app_net
  nginx:
    build: ./nginx
    volumes:
      - .:/code
    ports:
      - "3333:80"
    depends_on:
      - web
    networks:
      - app_net

networks :
  app_net:
