version: '2'
services:
  db:
    image: mysql
    environment:
        MYSQL_DATABASE: MdPManager
        MYSQL_USER: user
        MYSQL_PASSWORD: azerty
        MYSQL_ROOT_PASSWORD: azerty
    volumes:
        - ./bdd:/docker-entrypoint-initdb.d
    networks:
        - app_net
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_net

networks :
  app_net: